In [6]:
from sklearn.svm import LinearSVR
from sklearn import datasets

In [7]:
iris = datasets.load_iris()

In [12]:
x = iris["data"][:,3].reshape(-1, 1)

In [17]:
y = iris["target"]

In [18]:
svm_reg = LinearSVR(epsilon=1.5)

In [19]:
svm_reg.fit(x,y) # to fit values

LinearSVR(C=1.0, dual=True, epsilon=1.5, fit_intercept=True,
          intercept_scaling=1.0, loss='epsilon_insensitive', max_iter=1000,
          random_state=None, tol=0.0001, verbose=0)

In [30]:
svm_reg.predict([[1.4]])

array([0.5])

In [22]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

# SVR

In [3]:
from sklearn.svm import SVR

In [4]:
svm_svr = SVR(kernel="poly", degree=2, C=100, epsilon=0.1)

In [23]:
svm_svr.fit(x,y) # to fit values

SVR(C=100, cache_size=200, coef0=0.0, degree=2, epsilon=0.1, gamma='scale',
    kernel='poly', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [31]:
svm_svr.predict([[1.4]])

array([0.96951088])

In [34]:
svm_svr_linear = SVR(kernel="linear", degree=2, C=100, epsilon=0.1)

In [35]:
svm_svr_linear.fit(x,y)

SVR(C=100, cache_size=200, coef0=0.0, degree=2, epsilon=0.1, gamma='scale',
    kernel='linear', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [36]:
svm_svr_linear.predict([[1.4]])

array([1.20021811])

SVMs can also be used for outlier detection; see Scikit-Learn’s documentation
for more details.